#!/usr/bin/env fish
set sys (uname)
switch $sys
case '*Darwin*'
    cd ~/dotfiles/macos/
    ./load
    return
end

set folder_names (cat folders.txt)

for name in $folder_names
    rm -rf ~/.config/$name/
    cp -r $name/ ~/.config/
end

if test "$(uname)" = "Linux"
    rm -f ~/.xinitrc
    cp .xinitrc ~/.xinitrc
    rm -f ~/.bash_profile
    cp .bash_profile ~/.bash_profile
end

rm -f ~/.config/starship.toml
cp starship.toml ~/.config/starship.toml

rm -f ~/.xinitrc
cp .xinitrc ~/.xinitrc

rm -f ~/.bashrc
cp .bashrc ~/.bashrc

rm -f ~/.bash_profile
cp .bash_profile ~/.bash_profile
