format = " $all"
add_newline = false

[character]
success_symbol = "[ ](bg:green)"
error_symbol = "[ ](bg:red)"

[status]
disabled = false
format = "[$status]($style) "

[git_metrics]
disabled = false
