#!/usr/bin/expect

spawn bluetoothctl
expect "Agent registered"
send "menu gatt\r"
send "select-attribute /org/bluez/hci0/dev_F5_F3_E6_27_93_D2/service0010/char0011\r"
expect "#"
send "read\r"
sleep 1
send "exit\r"
expect eof
