#!/usr/bin/env bash

machine=$(cat /etc/machine-id)
machine_script="$HOME/.config/bspwm/$machine"
if test -f $machine_script
then
    $machine_script
fi


set -U SXHKD_SHELL /usr/bin/bash

## Configurations --------------------------------------------#
workspaces() {
	name=0
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'N' 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII'
		let name++
	done
}
workspaces

bspc config normal_border_color \#21222C
bspc config focused_border_color \#BD93F9
bspc config border_width 1
bspc config window_gap 0

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager picom polybar

# wallpaper
nitrogen --set-zoom-fill --random ~/wallpaper

# start polybar
polybar main &

# Notification daemon
dunst &

# Settings daemon
xsettingsd &

# Keybindings daemon
sxhkd &

# Power management
xfce4-power-manager &

# picom
picom &

# set default desktop to be I
sleep 1 && bspc desktop -f '^2' &
