#!/usr/bin/env bash

xrandr --output DP-0 --mode 3840x1080 --rate 120 &

set -U SXHKD_SHELL /usr/bin/bash

## Configurations --------------------------------------------#
workspaces() {
	name=0
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'N' 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII'
		let name++
	done
}
workspaces

bspc config focused_border_color \#BD93F9
bspc config border_width 1
bspc config window_gap 0
#bspc config split_ratio 0.50

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager picom polybar

# wallpaper
#feh --no-fehbg --bg-fill '/usr/share/backgrounds/nordic.jpg' &
feh --no-fehbg --bg-fill '/home/zx/Downloads/sunset.jpg' &

# start polybar
polybar main &

# Notification daemon
dunst &

# Settings daemon
xsettingsd &

# Keybindings daemon
sxhkd &

# Power management
xfce4-power-manager &

# picom
picom &
