#!/usr/bin/env bash

set -e

mkdir -p ~/screenshots/
file="$HOME/screenshots/$(date -Iseconds).png"

ts=$(date +%s)
countdown () {
  for sec in $(seq $1 -1 1); do
		dunstify -t 1100 --replace=$ts "screenshot in: $sec" &
		sleep 1
	done
}

chosen=$(rofi -steal-focus -l 5 -p 'screenshot' -dmenu -theme-str 'window {width:15%;}' <<EOF
desktop
area
window
in_5_seconds
in_10_seconds
EOF
)

case $chosen in
    "desktop")
	    sleep 0.5 && maim -f png "$file"
        ;;
    "area")
	    maim -f png -s "$file"
        ;;
    "window")
      maim -f png -i $(xdotool getactivewindow) "$file"
		;;
    "in_5_seconds")
	    countdown '5'
	    sleep 1 && maim -f png "$file"
		;;
    "in_10_seconds")
	    countdown '10'
	    sleep 1 && maim -f png "$file"
        ;;
    *) dunstify "invalid option: $chosen" exit 1 ;;
esac

xclip -selection clipboard -t image/png "$file"
pinta "$file"
