#!/usr/bin/env bash

e -c "redir! > /tmp/vimoldfiles | silent oldfiles | redir END | q" > /dev/null
file=$(sed '1d' /tmp/vimoldfiles | awk -F ": " '{print $2}' | rg '^/' | fzf)
test -f "$file" && e $file
