#!/opt/homebrew/bin/fish

# starship
rm -f ~/.config/starship.toml && cp ~/dotfiles/starship.toml ~/.config/starship.toml

# fish
rm -rf ~/.config/fish/ && cp -r ~/dotfiles/fish/ ~/.config/fish/
rm -f ~/.init.fish && cp ~/dotfiles/macos/.init.fish ~/.init.fish # extra macos stuff

# neovim
rm -rf ~/.config/nvim/ && cp -r ~/dotfiles/nvim/ ~/.config/nvim/

# alacritty
rm -rf ~/.config/alacritty/ && cp -r ~/dotfiles/macos/alacritty/ ~/.config/alacritty/

# yabai
rm -rf ~/.config/yabai/ && cp -r ~/dotfiles/macos/yabai/ ~/.config/yabai/

# skhd
rm -rf ~/.config/skhd/ && cp -r ~/dotfiles/macos/skhd/ ~/.config/skhd/
