#!/opt/homebrew/bin/fish

# starship
rm -f ~/.config/starship.toml && cp ~/dotfiles/starship.toml ~/.config/starship.toml

# fish
rm -rf ~/.config/fish/ && cp -r ~/dotfiles/fish/ ~/.config/fish/
/bin/cat ~/dotfiles/macos/pre_config.fish ~/dotfiles/fish/config.fish > ~/.config/fish/config.fish

# neovim
rm -rf ~/.config/nvim/ && cp -r ~/dotfiles/nvim/ ~/.config/nvim/

# alacritty
rm ~/.config/alacritty/alacritty.yml && cp ~/dotfiles/macos/alacritty.yml ~/.config/alacritty/
