#!/opt/homebrew/bin/fish

# starship
rm -f ~/dotfiles/starship.toml && cp ~/.config/starship.toml ~/dotfiles/starship.toml

# fish
rm -rf ~/dotfiles/fish/ && cp -r ~/.config/fish/ ~/dotfiles/fish/
rm ~/dotfiles/macos/.init.fish && cp ~/.init.fish ~/dotfiles/macos/.init.fish

# neovim
rm -rf ~/dotfiles/nvim/ && cp -r ~/.config/nvim/ ~/dotfiles/nvim/

# alacritty
rm ~/dotfiles/macos/alacritty.yml && cp ~/.config/alacritty/alacritty.yml ~/dotfiles/macos/alacritty.yml

cd ..
git add .
git diff --cached
git status
