#!/opt/homebrew/bin/fish

# starship
rm -f ~/dotfiles/starship.toml && cp ~/.config/starship.toml ~/dotfiles/starship.toml

# fish
rm -rf ~/dotfiles/fish/ && cp -r ~/.config/fish/ ~/dotfiles/fish/
rm ~/dotfiles/macos/.init.fish && cp ~/.init.fish ~/dotfiles/macos/.init.fish

# neovim
rm -rf ~/dotfiles/nvim/ && cp -r ~/.config/nvim/ ~/dotfiles/nvim/

# alacritty
rm -rf ~/dotfiles/macos/alacritty/ && cp ~/.config/alacritty/alacritty.yml ~/dotfiles/macos/alacritty/

# yabai
rm -rf ~/dotfiles/macos/yabai/ && cp -r ~/.config/yabai/ ~/dotfiles/macos/yabai/

# skhd
rm -rf ~/dotfiles/macos/skhd/ && cp -r ~/.config/skhd/ ~/dotfiles/macos/skhd/

cd ..
git add .
git diff --cached
git status
