#!/usr/bin/env bash

set -e

cat << EOF | fzf --preview "CMD={}; test -z \"\$CMD\" && ~/.config/hypr/general || eval \$CMD" \
	--layout reverse \
        --preview-window '70%,border-bottom' \
        --bind ctrl-d:preview-half-page-down \
        --bind ctrl-u:preview-half-page-up \
        --bind ctrl-j:preview-down \
        --bind ctrl-k:preview-up

neofetch
cpufetch
lsusb
bluetoothctl devices
ifconfig
mpstat -P ALL
iostat -p ALL
pidstat -T ALL
ping 8.8.8.8
ps aux
lscpu
lspci
cat /etc/passwd
wlr-randr
xrandr
lsblk --all
