#!/usr/bin/env bash

set -e

ADDRESS=$(hyprctl clients -j \
	| jq -r '.[] | select(.pid != -1) | "address:\(.address) class:\(.class) title:\(.title)"' \
	| column --table \
	| fzf --preview 'A=$(echo {} | cut -d" " -f1 | cut -d: -f2); hyprctl clients -j | jq -r ".[] | select(.address == \"$A\")"')

awk '{print $1}' <<< $ADDRESS | xargs hyprctl dispatch focuswindow
