#!/usr/bin/env bash

set -e

DESKTOP=$(find /usr/share/applications/ ~/.local/share/applications/ -name "*.desktop" \
	| fzf \
        --preview-window '70%' \
	--preview 'cat {}')

hyprctl dispatch exec gio launch $DESKTOP
