#!/usr/bin/env bash

set -e

APP=$(fd '.desktop$' $(tr ':' ' ' <<< $XDG_DATA_DIRS) --color=always \
	| fzf --ansi \
  --preview-window '70%' \
	--preview 'cat {}')

hyprctl dispatch exec gio launch $APP
