#!/usr/bin/env bash

set -e

SELECTION=$(hyprctl clients | rg '^Window ' --color=always | fzf --ansi --color=16 --inline-info)
test -n "$SELECTION" || exit
ADDRESS=$(cut -d' ' -f2 <<< "$SELECTION")
hyprctl dispatch focuswindow "address:0x$ADDRESS"
