#!/usr/bin/env bash

# change directory
builtin cd "$@"

# update dir history
mkdir -p ~/marks/
echo "$PWD" >> ~/marks/dir_history.txt

# # update git dir history
# git_dir=$(git rev-parse --show-toplevel 2> /dev/null) \
#   && echo "$git_dir" >> ~/marks/git_dir_history.txt \
#   || true
