#!/usr/bin/env bash

# Find the position of the first ':'
pos="${1%%:*}"
if [[ "$pos" == "$1" ]]; then
  # No ':' found, open the file directly
  nvim "$@" && return 0
fi

# Extract the file and line parts
file="${1%%:*}"
line="${1#*:}"

# Find the position of the second ':'
pos="${line%%:*}"
if [[ "$pos" == "$line" ]]; then
  # No second ':' found, open the file at the given line number
  nvim "$file" +$line "$@" && return 0
fi

# Extract column and line
column="${line#*:}"
line="${line%%:*}"

nvim "$file" "+call cursor($line, $column)" "$@"
