#!/usr/bin/env bash

pos=$(expr index "$1" ':')
test $pos -eq 0 && $EDITOR $1 && return 0

file=${1:0:pos-1}
line=${1:pos}

pos=$(expr index "$line" ':')
test $pos -eq 0 && $EDITOR $file +$line && return 0

column=${line:pos}
line=${line:0:pos-1}
$EDITOR "$file" "+call cursor($line, $column)"
