#!/usr/bin/env bash

selection=$(rg "$READLINE_LINE" --line-number --color=always --hidden --no-ignore 2> /dev/null \
  | fzf --delimiter=':' \
        --preview='bat --number --color=always --theme=Dracula --highlight-line={2} {1}' \
        --preview-window='noborder,+{2}/2' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --exit-0 \
      )

test -z "$selection" && return

file_name=$(cut -d':' -f1 <<< "$selection")
line_number=$(cut -d':' -f2 <<< "$selection")
nvim +"$line_number" "$file_name" +"norm zz"
