#!/usr/bin/env bash

word="$(source ~/.config/bash/get_last_word_before_cursor)"

tmux capture-pane -pe | tr ' ' '\n' > /tmp/fzf-tmux
tmux capture-pane -pe | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' >> /tmp/fzf-tmux

selected="$(cat /tmp/fzf-tmux \
  | awk '!x[$0]++' \
  | fzf --layout=reverse --height=7 --query=$word)" || return

post_cursor="${READLINE_LINE:$READLINE_POINT}"
pre_cursor="${READLINE_LINE:0:$(($READLINE_POINT-${#word}))}$selected"
READLINE_LINE="$pre_cursor$post_cursor"
READLINE_POINT=${#pre_cursor}
