#!/usr/bin/env bash

SELECTION=$(fd --hidden --no-ignore --type=executable | xargs eza --sort=none --list-dirs --color=always --icons=always 2> /dev/null \
  | fzf --preview='file {2} && ldd {2}' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --preview-window=noborder \
        | cut --delimiter=' ' --fields=2
      )

test -x "$SELECTION" && ./"$SELECTION"
