#!/usr/bin/env bash

ORI_DIR="$PWD"
CUR_DIR="$PWD"

while true; do

  SELECTION=$(eza --color=always --all --dereference --icons=always "$CUR_DIR" \
    | fzf --preview='(test -f {2} && bat --number --color=always --theme=Dracula {2}) || (test -d {2} && eza --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git {2})' \
          --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up,left:become(echo ".."),right:accept' \
          --header="$CUR_DIR" \
    | cut -d' ' -f2)

  # If no selection was made
  if test -z "$SELECTION"; then
    if test "$CUR_DIR" != "$ORI_DIR"; then
      X_INPUT=$(sed "s|$ORI_DIR/|./|;s|$HOME/|~/|" <<< "$CUR_DIR")
      . ~/.config/bash/insert_at_cursor
    fi
    return
  fi

  FULL_SELECTION="$CUR_DIR/$SELECTION"

  # if the selection is a directory, navigate into it and continue
  if test -d "$FULL_SELECTION"; then
    CUR_DIR=$(realpath "$FULL_SELECTION")
    continue
  fi


  # if the selection is a file, insert its path at the cursor
  if test -f "$FULL_SELECTION"; then
    X_INPUT=$(sed "s|$ORI_DIR/|./|;s|$HOME/|~/|" <<< "$FULL_SELECTION")
    . ~/.config/bash/insert_at_cursor
    return
  fi

done
