#!/usr/bin/env bash

X_LEFT_WORD="$(. ~/.config/bash/x_left_word)"
X_INPUT=$(eza --all --color=always --icons=always --recurse --oneline --absolute \
  | rg -v '^$|:$' \
  | sed "s|$PWD/|./|" \
  | fzf --preview='(test -f {2} && bat --number --color=always {2}) || (test -d {2} && eza --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git {2})' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --query="$X_LEFT_WORD" \
        --scheme=path \
  | cut -d' ' -f2)

if test -f "$X_INPUT"; then
  READLINE_LINE=""
  READLINE_POINT=0
  "$EDITOR" "$X_INPUT"
elif test -d "$X_INPUT"; then
  if cd "$X_INPUT"; then
    READLINE_LINE=""
    READLINE_POINT=0
    echo $ cd "$X_INPUT"
    . ~/.config/bash/prompt
  fi
fi
