#!/usr/bin/env bash

word="$(. ~/.config/bash/get_last_word_before_cursor)"

selected=$(eza --all --color=always --icons=always --recurse --oneline --absolute --classify=always | rg '\*$' | sed "s|$PWD/||" | sed 's/.$//' \
  | fzf --preview='test "$(dd bs=2 count=1 < {2} 2> /dev/null)" = "#!" && bat --theme=Dracula --number --color=always {2} || (file {2} && ldd {2})' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --preview-window=noborder --exit-0 \
        | cut -d' ' -f2
      )

test -z "$selected" && return
. ~/.config/bash/insert_at_cursor "./$selected"
