#!/usr/bin/env bash

dir=$(tac ~/marks/git_dir_history.txt \
  | awk '!x[$0]++' \
  | tee /tmp/git_dir_history.txt \
  | xargs eza --sort=none --list-dirs --color=always 2> /dev/null \
  | fzf --ansi --no-sort --color=16 --inline-info --query="$PWD" \
    )

tac /tmp/git_dir_history.txt > ~/marks/git_dir_history.txt

test -n "$dir" && cd "$dir"
