#!/usr/bin/env bash

selection=$(rg "$READLINE_LINE" --line-number --color=always --hidden --no-ignore 2> /dev/null \
  | fzf --delimiter=':' \
        --preview='bat --number --color=always --theme=Dracula --highlight-line={2} {1}' \
        --preview-window='noborder,+{2}/2' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
      )

test -z "$selection" && return

# <filename>:<line_number>:<line_content> -> <filename>:<line_number>
file_with_line=$(cut -d: -f1-2 <<< "$selection")
e "$file_with_line" +"norm zz"
