#!/usr/bin/env bash

X_LEFT_WORD="$(. ~/.config/bash/x_left_word)"
X_INPUT="$(tmux capture-pane -pe \
  | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
  | awk '!x[$0]++' \
  | fzf --layout=reverse --height=7 --query="$X_LEFT_WORD")" || return

. ~/.config/bash/insert_at_cursor
