#!/usr/bin/env bash

selection=$(tac ~/.cmd_line_history \
  | awk '!x[$0]++' \
  | tee /tmp/.cmd_line_history \
  | bat --color=always --language=bash --style=plain \
  | fzf --scheme=history --no-sort --query "$READLINE_LINE")
test -z "$selection" && return

tac /tmp/.cmd_line_history > ~/.cmd_line_history

READLINE_LINE="$selection" && READLINE_POINT=${#READLINE_LINE}
