#!/usr/bin/env bash

X_LEFT_WORD="$(. ~/.config/bash/x_left_word)"

tmux capture-pane -pe | tr ' ' '\n' > /tmp/fzf-tmux
tmux capture-pane -pe | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' >> /tmp/fzf-tmux

X_INPUT="$(cat /tmp/fzf-tmux \
  | awk '!x[$0]++' \
  | fzf --layout=reverse --height=7 --query=$X_LEFT_WORD)" || return

. ~/.config/bash/insert_at_cursor "$X_INPUT"
