#!/usr/bin/env bash

selection=$(nvim --headless +':oldfiles' +':qa!' 2>&1 \
  | cut --delimiter=' ' --fields=2 \
  | sed 's/.$//' \
  | xargs eza --sort=none --color=always --icons=always 2> /dev/null \
  | fzf --no-sort --query "$PWD/" \
      --preview='bat --number --color=always --theme=Dracula {2}' \
      --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
      --preview-window=noborder \
      | cut --delimiter=' ' --fields=2
    )

test -n "$selection" && nvim "$selection"
