#!/usr/bin/env bash

SELECTION=$(fd --hidden --no-ignore | xargs eza --sort=none --list-dirs --color=always --icons=always 2> /dev/null \
  | fzf --preview='(test -f {2} && bat --number --color=always --theme=Dracula {2}) || (test -d {2} && exa --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git {2})' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --preview-window=noborder \
        | cut --delimiter=' ' --fields=2
      )

test -z "$SELECTION" && return

# insert selected directory at cursor
POST_CURSOR="${READLINE_LINE:READLINE_POINT}"
PRE_CURSOR="${READLINE_LINE:0:READLINE_POINT}${SELECTION}"
READLINE_POINT=${#PRE_CURSOR}
READLINE_LINE="$PRE_CURSOR$POST_CURSOR"
