#!/usr/bin/env bash

SELECTION=$(nvim --headless +':oldfiles' +':qa!' 2>&1 \
  | cut -d' ' -f2 \
  | sed 's/.$//' \
  | xargs eza --sort=none --color=always --icons=always 2> /dev/null \
  | sed "s| .*$HOME| ~|" \
  | fzf --no-sort --query "${PWD/#$HOME/\~}" \
      --preview="bat --number --color=always --theme=Dracula \$(sed \"s|^~|$HOME|\" <<< '{2}')" \
      --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
      --preview-window=noborder \
      | cut -d' ' -f2
    )

test -z "$SELECTION" && return
SELECTION=${SELECTION/#\~/$HOME}
test -n "$SELECTION" && nvim "$SELECTION"
