#!/usr/bin/env bash

selection=$(fd --hidden --no-ignore | xargs eza --sort=none --list-dirs --color=always --icons=always 2> /dev/null \
  | fzf --ansi --color=16 --inline-info \
        --preview='(test -f {2} && bat --number --color=always --theme=Dracula {2}) || (test -d {2} && exa --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git {2})' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --preview-window=noborder \
        --query="$READLINE_LINE" \
        | cut --delimiter=' ' --fields=2
      )

test -z "$selection" && return
test -d "$selection" && cd "$selection" && return
test -x "$selection" && "$selection" && return
test -f "$selection" && nvim "$selection" && return
echo "$selection" not found && return 1
