#!/usr/bin/env bash

line="$(tmux capture-pane -pe \
  | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
  | awk '!x[$0]++' \
  | fzf --layout=reverse --height=1)" || return

pre_cursor="${READLINE_LINE:0:$READLINE_POINT}$line"
READLINE_LINE="$pre_cursor${READLINE_LINE:$READLINE_POINT}"
READLINE_POINT=${#pre_cursor}
