#!/usr/bin/env bash

word="$(. ~/.config/bash/get_last_word_before_cursor)"
selected="$(tmux capture-pane -pe \
  | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
  | awk '!x[$0]++' \
  | fzf --layout=reverse --height=7 --query="$word")" || return

. ~/.config/bash/insert_at_cursor
