#!/usr/bin/env bash

HOME_SYM="$(realpath $HOME)"
X_INPUT=$(tac ~/marks/dir_history.txt \
  | awk '!x[$0]++' \
  | tee /tmp/dir_history.txt \
  | xargs eza --sort=none --list-dirs --icons=always --color=always 2> /dev/null \
  | sed "s|$PWD/|./|;s|$HOME_SYM|~|;s|$HOME|~|" \
  | fzf --preview="eza --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git \$(sed \"s|^~|$HOME|\" <<< '{2}')" \
        --query="$(</tmp/readline_line)" \
        --scheme=path --no-sort \
  | cut -d' ' -f2)

tac /tmp/dir_history.txt > ~/marks/dir_history.txt

test -z "$X_INPUT" && return
X_INPUT=${X_INPUT/#\~/$HOME}
if test -d "$X_INPUT"; then
  if cd "$X_INPUT"; then
    READLINE_LINE=""
    READLINE_POINT=0
    echo $ cd "$X_INPUT"
    . ~/.config/bash/prompt
  fi
fi
