#!/usr/bin/env bash

# Extract the word from the left of the cursor and export it as X_LEFT_WORD
# e.g. text: "hello good|bye human" -> X_LEFT_WORD="good"

line="$READLINE_LINE"
point="$READLINE_POINT"
test "$point" -eq 0 && return

# Check if the character BEFORE the cursor is whitespace
[[ "${line:point-1:1}" =~ [[:space:]] ]] && return

# Extract the last word normally
before_cursor="${line:0:point}"
before_cursor="${before_cursor%"${before_cursor##*[![:space:]]}"}"
[[ "$before_cursor" =~ [^[:space:]]+$ ]] && printf "${BASH_REMATCH[0]}"
