#!/usr/bin/fish

set hex_value (~/.config/sxhkd/scripts/skeletyl_battery \
    | rg Attribute -A 1                                 \
    | tail --lines 1                                    \
    | cut -d \r -f 2                                    \
    | cut -d ' ' -f 3)

echo "hex_value: $hex_value"

set dec_value (math "0x$hex_value")
dunstify "skeletyl battery level: $dec_value%"
