#!/usr/bin/env bash

# Additional configurations (if any)
test -f ~/.bspwmrc && . ~/.bspwmrc

# Setup workspaces
workspaces() {
	name=1
	for monitor in $(bspc query --monitors); do
		# bspc monitor $monitor -n $name -d 'N' 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII'
		bspc monitor $monitor --rename $name --reset-desktops 1 2 3 4 5 6 7 8 9
		let name++
	done
}
workspaces

# Set bspwm configurations
bspc config normal_border_color \#21222C
bspc config focused_border_color \#BD93F9
bspc config border_width 1
bspc config window_gap 0

# # Set wallpaper
# nitrogen --set-zoom-fill --random ~/wallpaper

# Launch polybar
polybar main &

# Notification daemon
dunst &

# Keybindings daemon
sxhkd &

# # Compositor
# picom --backend egl &
