[colors]
transparent_background_colors = false

[colors.bright]
black = "#6272a4"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.hints.end]
background = "#282a36"
foreground = "#f1fa8c"

[colors.hints.start]
background = "#f1fa8c"
foreground = "#282a36"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#000000"
bright_foreground = "#ffffff"
foreground = "#f8f8f2"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[window]
opacity = 0.7
decorations = "None"

[terminal.shell]
program = "/usr/bin/env"
args = [ "bash" ]

#
# [hints]
# alphabet = "123456789"
#
# # Open URLs with xdg-open
# [[hints.enabled]]
# command = "xdg-open"
# post_processing = true
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
#
# [hints.enabled.binding]
# key = "O"
# mods = "Alt"
#
# # Copy line to clipboard
# [[hints.enabled]]
# action = "Copy"
# post_processing = true
# regex = "[^ ]+ "
#
# [hints.enabled.binding]
# key = "W"
# mods = "Alt"
#
# # Copy word to clipboard
# [[hints.enabled]]
# action = "Copy"
# post_processing = true
# regex = ".+ "
#
# [hints.enabled.binding]
# key = "L"
# mods = "Alt"
