#!/usr/bin/env bash

dir=$(tac ~/marks/git_dir_history.txt \
  | awk '!x[$0]++' \
  | tee /tmp/git_dir_history.txt \
  | fzf --no-sort)
tac /tmp/git_dir_history.txt > ~/marks/git_dir_history.txt

test -d "$dir" && cd "$dir"
