#!/usr/bin/env bash

path=$(fd --color=always --hidden --no-ignore | fzf --ansi)
pre_cursor="${READLINE_LINE:0:$READLINE_POINT}$path"
test -n "$path" \
  && READLINE_LINE="$pre_cursor${READLINE_LINE:$READLINE_POINT}" \
  && READLINE_POINT=${#pre_cursor}
