#!/usr/bin/env bash

selection=$(history \
  | tac \
  | rg "$READLINE_LINE" \
  | fzf --no-sort --query "$READLINE_LINE" --inline-info)

test -n "$selection" \
  && READLINE_LINE="${selection:7}" \
  && READLINE_POINT=${#READLINE_LINE}
