#!/usr/bin/env bash

line="$(tmux capture-pane -pe \
  | awk '!x[$0]++' \
  | fzf --ansi --layout=reverse --height=30%)" || return

pre_cursor="${READLINE_LINE:0:$READLINE_POINT}$line"
READLINE_LINE="$pre_cursor${READLINE_LINE:$READLINE_POINT}"
READLINE_POINT=${#pre_cursor}
