#!/usr/bin/env bash

selection=$(history \
  | rg "$READLINE_LINE" \
  | fzf --tac --no-sort --layout=reverse --color=16 --query "$READLINE_LINE" --inline-info)

test -n "$selection" \
  && READLINE_LINE="${selection:7}" \
  && READLINE_POINT=${#READLINE_LINE}
