#!/usr/bin/env bash

pos=$READLINE_POINT
line=$READLINE_LINE

last_char="${line:pos-1}"
last_char="${last_char//[[:space:]]/}"

if [ -z "$last_char" ]; then
  unset word
else
  word=$(awk '{print $NF}' <<< "${line:0:$pos}")
fi

res=$(tmux capture-pane -p -e | fzf --ansi --no-sort --query "$word")
READLINE_LINE="$READLINE_LINE${res}"
READLINE_POINT=${#READLINE_LINE}
