#!/usr/bin/env bash

while true; do
  selection=$(fd . "$PWD" --max-depth=1 --color=always --hidden --no-ignore \
    | fzf --ansi --color=16 --inline-info \
          --preview='(test -f {} && bat --number --color=always --theme=Dracula {}) || (test -d {} && exa --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git {})' \
          --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up,left:become(echo ".."),right:accept' \
          --preview-window=noborder \
  )

  test -z "$selection" && break
  test -d "$selection" && cd "$selection"
  test -f "$selection" && nvim "$selection"
done
