#!/usr/bin/env bash

selection=$(fd "$READLINE_LINE" --color=always \
  | fzf --ansi --inline-info \
        --preview='test -f {} && bat --number --color=always --theme=Dracula {} || test -d {} && exa --color=always --icons --sort accessed --color-scale=all --no-quotes --long --binary --time-style long-iso --git {}' \
        --bind='ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,ctrl-j:preview-down,ctrl-k:preview-up' \
        --preview-window=noborder \
      )

test -z "$selection" && return
test -d "$selection" && cd "$selection" && return
test -f "$selection" && nvim "$selection" && return
echo "$selection" is not a file or directory && return 1
